Repository hpi-schul-cloud/end-to-end-tests, pull requests merged in 2020-11, with the labels that each got.

#213 Feature/sc 6654 reduce lines of code per method homework feature
  features/createTask.feature
  features/homework.feature
  features/task.feature
  page-objects/pages/HMWRKAddEditHomeworkPage.js
  page-objects/pages/HMWRKHomeworkPage.js
  page-objects/pages/NavigationTopPage.js
  page-objects/pages/TASKAddEditTaskPage.js
  page-objects/pages/TASKListPage.js
  page-objects/pages/TASKPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  page-objects/pages/coursePages/CRSSCourseHomeworksPage.js
  page-objects/pages/coursePages/CRSSGeneralCoursePage.js
  shared_steps/common-steps.js
  step_definitions/course-steps.js
  step_definitions/createTask-steps.js
  step_definitions/editTask-steps.js
  step_definitions/homework-steps.js
  step_definitions/task-steps.js
Labels: waiting for review

#224 User Profile Steps - Improve Terms In Cucumber Steps
  features/adminCreateClassWithoutParticipants.feature
  features/adminCrossSchoolPermission.feature
  features/administration.feature
  features/changeLanguage.feature
  features/copyCourse.feature
  features/course.feature
  features/createTask.feature
  features/createTeam.feature
  features/editClass.feature
  features/editProfile.feature
  features/editTask.feature
  features/login.feature
  features/navigationLeft.feature
  features/news.feature
  features/searchCourse.feature
  features/sendConsentFormEmail.feature
  features/task.feature
  features/topic.feature
  features/versions.feature
  features/visibilityOfMenuItems.feature
  page-objects/pages/AccountPage.js
  page-objects/pages/generalPagesBeforeLogin/LoginPage.js
  runtime/helpers/mailCatcher.js
  shared_steps/common-steps.js
  step_definitions/login-steps.js
  step_definitions/sendConsentFormEmail-steps.js
  step_definitions/versions.js
  step_definitions/wrongPasswordLogin-steps.js
Labels: waiting for review

#220 Feature/sc 6662 private homeworks are shown
  features/navigationLeft.feature
  features/news.feature
  features/task.feature
  features/visibilityOfMenuItems.feature
  page-objects/pages/DashboardPage.js
  page-objects/pages/TASKListPage.js
  runtime/helpers/dateTimeHelpers.js
  step_definitions/navigationLeft-steps.js
  step_definitions/task-steps.js
Labels: waiting for review

#225 OPS-1297 - Add Changelog github action.
  .github/workflows/require_changelog.yml
  CHANGELOG.md
Labels: ready to merge

#230 teams, topics, class steps - improve terms in cucumber steps
  CHANGELOG.md
  features/administration.feature
  features/copyCourse.feature
  features/course.feature
  features/createClassWithoutParticipants.feature
  features/createTask.feature
  features/createTeam.feature
  features/crossSchoolPermission.feature
  features/editClass.feature
  features/editTask.feature
  features/navigationLeft.feature
  features/news.feature
  features/searchCourse.feature
  features/task.feature
  features/topic.feature
  features/versions.feature
  features/visibilityOfMenuItems.feature
  page-objects/pages/DashboardPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  page-objects/pages/coursePages/CRSSCourseListPage.js
  page-objects/pages/teamsPages/TMSAddEditTeamPage.js
  page-objects/pages/teamsPages/TMSTeamListPage.js
  runtime/helpers/waitHelpers.js
  step_definitions/administartion-steps.js
  step_definitions/course-steps.js
  step_definitions/createClassWithoutParticipants-steps.js
  step_definitions/createTeam-steps.js
  step_definitions/task-steps.js
  step_definitions/topic-steps.js
Labels: waiting for review

#238 SC-7733 - user can't login anymore
  CHANGELOG.md
  features/administration.feature
  page-objects/pages/administrationPages/ADMNSTRTNAdministerTeachersPage.js
  page-objects/pages/administrationPages/ADMNSTRTNAdministrationOverviewPage.js
  page-objects/pages/administrationPages/ADMNSTRTNEditDeleteTeacherPage.js
  step_definitions/administartion-steps.js
Labels: waiting for review

#241 fixed changelog github action
  .github/workflows/require_changelog.yml
  CHANGELOG.md
Labels: waiting for review

#244 grammatical correction managment->management
  features/management_classes/createClass.feature
  features/management_classes/editClass.feature
  features/management_school/school.feature
  features/management_students/createStudent.feature
  features/management_students/deleteStudent.feature
  features/management_students/editStudent.feature
  features/management_teachers/deleteTeacher.feature
  step_definitions/management_classes/createClass_steps.js
  step_definitions/management_classes/editClass_steps.js
  step_definitions/management_school/school_steps.js
  step_definitions/management_students/createStudent_steps.js
  step_definitions/management_students/deleteStudent_steps.js
  step_definitions/management_students/editStudent_steps.js
  step_definitions/management_teachers/createTeacher_steps.js
  step_definitions/management_teachers/deleteTeacher_steps.js
  step_definitions/management_teachers/editTeacher_steps.js
Labels: waiting for review

#245 SC - 7329 adjust qa t cs to initial db idea
  CHANGELOG.md
  features/courses/copyCourse.feature
  features/courses/createCourse.feature
  features/courses/deleteCourse.feature
  features/courses/editCourse.feature
  features/courses/searchCourse.feature
  features/courses_topics/createTopic.feature
  features/courses_topics/deleteTopic.feature
  features/courses_topics/editTopic.feature
  features/dashboard/task.feature
  features/management_classes/createClass.feature
  features/management_school/school.feature
  features/management_students/createStudent.feature
  features/management_students/editStudent.feature
  features/navigation_bar_left/leftNavigationBar.feature
  features/navigation_bar_top/firstLogin.feature
  features/navigation_bar_top/wrongLogin.feature
  features/news/createNews.feature
  features/tasks/createTask.feature
  features/tasks/deleteTask.feature
  features/tasks/editTask.feature
  features/tasks/submitTask.feature
  features/teams/createTeam.feature
  features/user_settings/changeLanguageMenu.feature
  features/user_settings/changePassword.feature
  page-objects/apiTest.js
  page-objects/pages/DashboardPage.js
  page-objects/pages/coursePages/CRSSCourseListPage.js
  page-objects/pages/generalPagesBeforeLogin/LoginPage.js
  shared_steps/common-steps.js
  step_definitions/courses/deleteCourse_steps.js
Labels: waiting for review

#246 SC-7735 - Removed user in not visible in team anymore
  CHANGELOG.md
  features/management_students/deleteStudent.feature
  page-objects/pages/teamsPages/TMSTeamListPage.js
  step_definitions/management_students/editStudent_steps.js
  step_definitions/teams/createTeam_steps.js
Labels: waiting for review

#247 SC-7736 - User should not be able to use forgot password functionality
  CHANGELOG.md
  features/management_students/deleteStudent.feature
  page-objects/pages/generalPagesBeforeLogin/LoginPage.js
  page-objects/pages/generalPagesBeforeLogin/StartPageBeforeLogin.js
  runtime/helpers/mailCatcher.js
  shared_steps/common-steps.js
  step_definitions/management_students/editStudent_steps.js
Labels: waiting for review

#248 Task/sc 5167 student13 years can register
  features/management_students/createStudent.feature
  features/management_students/editStudent.feature
  page-objects/pages/generalPagesBeforeLogin/RegistrationPage.js
  page-objects/pages/managementPages/ManageStudentsPage.js
  runtime/helpers/mailCatcher.js
  shared_steps/common-steps.js
  step_definitions/management_students/createStudent_steps.js
  step_definitions/management_students/editStudent_steps.js
Labels: waiting for review

#252 SC-6814 - deleting class
  CHANGELOG.md
  features/management_classes/deleteClass.feature
  page-objects/pages/managementPages/ManageClassPage.js
  page-objects/pages/managementPages/ManageStudentPage.js
  step_definitions/management_classes/deleteClass_steps.js
  step_definitions/management_classes/editClass_steps.js
Labels: waiting for review

#254 Hotfix/1/SC-7878 - fixed failing tests
  CHANGELOG.md
  page-objects/pages/HMWRKAddEditHomeworkPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  page-objects/pages/teamsPages/TMSTeamMembersPage.js
  step_definitions/course-steps.js
Labels: DO_NOT_MERGE

#253 Feature/sc 5797 dashboard regular homeworks are shown for a teacher
  CHANGELOG.md
  features/courses/createCourse.feature
  features/dashboard/task.feature
  page-objects/pages/AccountPage.js
  page-objects/pages/DashboardPage.js
  page-objects/pages/HMWRKAddEditHomeworkPage.js
  page-objects/pages/TASKAddEditTaskPage.js
  page-objects/pages/TASKListPage.js
  page-objects/pages/TASKPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  page-objects/pages/coursePages/CRSSAddEditTopicPage.js
  page-objects/pages/managementPages/ManageClassPage.js
  page-objects/pages/managementPages/ManageClassesPage.js
  page-objects/pages/teamsPages/TMSTeamMembersPage.js
  runtime/helpers/elementHelpers.js
  step_definitions/course-steps.js
  step_definitions/dashboard/task_steps.js
Labels: waiting for review
