Repository hpi-schul-cloud/end-to-end-tests, pull requests merged in 2020-09, with the labels that each got.

#160 SC-5796 add methods to wait helper
  runtime/helpers/waitHelpers.js
Labels: waiting for review

#155 Feature/sc 5822 refactoring create navigation bottom page
  page-objects/pages/NavigationBottomPage.js
Labels: ready to merge, waiting for review

#157 transfer courseData sharedObject to the new Page Object structure part 1
  features/copyCourse.feature
  features/homework.feature
  page-objects/pages/HMWRKAddEditHomeworkPage.js
  page-objects/pages/HMWRKHomeworkListPage.js
  page-objects/pages/HMWRKHomeworkPage.js
  page-objects/pages/NavigationTopPage.js
  page-objects/pages/coursePages/CRSSAddEditTopicPage.js
  page-objects/pages/coursePages/CRSSCourseGroupsPage.js
  page-objects/pages/coursePages/CRSSCourseHomeworksPage.js
  page-objects/pages/coursePages/CRSSCourseListPage.js
  page-objects/pages/coursePages/CRSSCourseToolsPage.js
  page-objects/pages/coursePages/CRSSCourseTopicsPage.js
  page-objects/pages/coursePages/CRSSEditCopyCoursePage.js
  page-objects/pages/coursePages/CRSSGeneralCoursePage.js
  page-objects/pages/generalPagesBeforeLogin/LogoutPage.js
  shared-objects/courseData.js
  step_definitions/copyCourse-steps.js
  step_definitions/createCourse-steps.js
  step_definitions/createTask-steps.js
  step_definitions/homework-steps.js
Labels: waiting for review

#166 SC-5793 - student logs in - no external system
  features/login.feature
  page-objects/pages/DashboardPage.js
  page-objects/pages/generalPagesBeforeLogin/LoginPage.js
  runtime/helpers/APIhelpers.js
  step_definitions/login-steps.js
Labels: waiting for review

#170 SC - 5285 teacher creates a private homework
  features/homework.feature
  page-objects/pages/HMWRKAddEditHomeworkPage.js
  page-objects/pages/HMWRKHomeworkListPage.js
  step_definitions/homework-steps.js
Labels: waiting for review

#162 Feature/sc 5787 create navigation top page
  page-objects/pages/NavigationTopPage.js
Labels: ready to merge

#175 Feature/sc 6661 refactoring wait helpers methods
  package-lock.json
  package.json
  page-objects/pages/HMWRKAddEditHomeworkPage.js
  page-objects/pages/HMWRKHomeworkListPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  page-objects/pages/coursePages/CRSSCourseGroupsPage.js
  page-objects/pages/coursePages/CRSSCourseHomeworksPage.js
  page-objects/pages/coursePages/CRSSCourseListPage.js
  page-objects/pages/coursePages/CRSSCourseToolsPage.js
  page-objects/pages/coursePages/CRSSCourseTopicsPage.js
  page-objects/pages/coursePages/CRSSEditCopyCoursePage.js
  page-objects/pages/coursePages/CRSSGeneralCoursePage.js
  page-objects/pages/generalPagesBeforeLogin/StartPageBeforeLogin.js
  runtime/helpers/elementHelpers.js
  runtime/helpers/sharedHelpers.js
  runtime/helpers/waitHelpers.js
  runtime/world.js
Labels: waiting for review

#163 Add package that allows intellisense to list suggestions for driver
  jsconfig.json
  package-lock.json
  package.json
Labels: waiting for review

#183 Moving selectors above module.exports
  page-objects/pages/DashboardPage.js
  page-objects/pages/HMWRKAddEditHomeworkPage.js
  page-objects/pages/HMWRKHomeworkListPage.js
  page-objects/pages/HMWRKHomeworkPage.js
  page-objects/pages/NWSAddEditNewsPage.js
  page-objects/pages/NWSNewsListPage.js
  page-objects/pages/NavigationTopPage.js
  page-objects/pages/administrationPages/ADMNSTRTNAdministerClassesPage.js
  page-objects/pages/administrationPages/ADMNSTRTNAdministerStudentsPage.js
  page-objects/pages/administrationPages/ADMNSTRTNAdministrationOverviewPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  page-objects/pages/coursePages/CRSSCourseGroupsPage.js
  page-objects/pages/coursePages/CRSSCourseHomeworksPage.js
  page-objects/pages/coursePages/CRSSCourseListPage.js
  page-objects/pages/coursePages/CRSSCourseToolsPage.js
  page-objects/pages/coursePages/CRSSCourseTopicsPage.js
  page-objects/pages/coursePages/CRSSEditCopyCoursePage.js
  page-objects/pages/coursePages/CRSSGeneralCoursePage.js
  page-objects/pages/generalPagesBeforeLogin/LoginPage.js
  page-objects/pages/generalPagesBeforeLogin/StartPageBeforeLogin.js
  page-objects/pages/teamsPages/TMSTeamListPage.js
  runtime/helpers/waitHelpers.js
  shared_steps/common-steps.js
  step_definitions/copyCourse-steps.js
  step_definitions/visibilityOfAdministrationTabsForAdmin-steps.js
  step_definitions/visibilityOfDialoguesTabsForTheTeacher-steps.js
Labels: waiting for review

#184 SC - 6821 - delete course
  features/course.feature
  page-objects/pages/coursePages/CRSSCourseListPage.js
  page-objects/pages/coursePages/CRSSEditCopyCoursePage.js
  step_definitions/course-steps.js
Labels: waiting for review
