Repository hpi-schul-cloud/end-to-end-tests, pull requests merged in 2020-08, with the labels that each got.

#107 add tests for admin
  features/adminCrossSchoolPermission.feature
  page-objects/administration.js
  runtime/helpers/axiosHelper.js
  step_definitions/adminCrossSchoolPermission-steps.js
Labels: waiting for review

#123 add fix for misleading paths
  step_definitions/adminCrossSchoolPermission-steps.js
Labels: waiting for review

#131 Feature/sc 5742 changed settings icon
  page-objects/copyCourse.js
Labels: ready to merge

#125 SC-5742 - replaced the settings icons
  page-objects/copyCourse.js
Labels: WIP

#105 SC-4673 CKEditor update
  page-objects/copyCourse.js
  page-objects/createTask.js
  page-objects/homework.js
Labels: DO_NOT_MERGE

#144 fix hardcoded id
  page-objects/administration.js
Labels: waiting for review

#147 SC-5915: homework dashboard
  page-objects/homework.js
  page-objects/pages/HMWRKAddEditHomeworkPage.js
  page-objects/pages/HMWRKHomeworkListPage.js
Labels: waiting for review

#148 Feature/sc 5786 login data.js
  features/createTask.feature
  features/createTeam.feature
  features/homework.feature
  features/teacherLogin.feature
  features/wrongPasswordLogin.feature
  page-objects/homework.js
  page-objects/pages/DashboardPage.js
  page-objects/pages/HMWRKHomeworkListPage.js
  page-objects/pages/NWSAddEditNewsPage.js
  page-objects/pages/generalPagesBeforeLogin/LoginPage.js
  runtime/helpers/APIhelpers.js
  shared-objects/loginData.js
  shared_steps/common-steps.js
  shared_steps/firstLogin.js
  step_definitions/adminCreateClassWithoutParticipants-steps.js
  step_definitions/adminCrossSchoolPermission-steps.js
  step_definitions/adminLogin-steps.js
  step_definitions/administartion-steps.js
  step_definitions/copyCourse-steps.js
  step_definitions/createTask-steps.js
  step_definitions/createTeam-steps.js
  step_definitions/homework-steps.js
  step_definitions/news-steps.js
  step_definitions/pupilLogin-steps.js
  step_definitions/teacherLogin-steps.js
  step_definitions/visibilityOfAdministrationTabsForAdmin-steps.js
  step_definitions/visibilityOfDialoguesTabsForTheTeacher-steps.js
  step_definitions/wrongPasswordLogin-steps.js
Labels: WIP

#150 Feature/sc 5799 merge login steps avoid duplicates
  features/addPupilToTheCourse.feature
  features/adminCreateClassWithoutParticipants.feature
  features/adminCrossSchoolPermission.feature
  features/adminLogin.feature
  features/administration.feature
  features/copyCourse.feature
  features/createCourse.feature
  features/createTask.feature
  features/createTeam.feature
  features/editProfile.feature
  features/homework.feature
  features/login.feature
  features/navigationLeft.feature
  features/news.feature
  features/pupilLogin.feature
  features/searchCourse.feature
  features/teacherLogin.feature
  features/visibilityOfDialoguesTabsForTheAdmin.feature
  features/visibilityOfDialoguesTabsForTheTeacher.feature
  features/wrongPasswordLogin.feature
  page-objects/homework.js
  page-objects/pages/generalPagesBeforeLogin/LoginPage.js
  runtime/helpers/waitHelpers.js
  shared_steps/common-steps.js
  shared_steps/firstLogin.js
  step_definitions/addPupilsToTheCourse-steps.js
  step_definitions/adminCreateClassWithoutParticipants-steps.js
  step_definitions/copyCourse-steps.js
  step_definitions/createCourse-steps.js
  step_definitions/createTask-steps.js
  step_definitions/createTeam-steps.js
  step_definitions/homework-steps.js
  step_definitions/login-steps.js
  step_definitions/news-steps.js
  step_definitions/pupilLogin-steps.js
  step_definitions/teacherLogin-steps.js
  step_definitions/visibilityOfAdministrationTabsForAdmin-steps.js
  step_definitions/visibilityOfDialoguesTabsForTheTeacher-steps.js
Labels: waiting for review

#154 Feature/sc 5784 refactor first login.js
  features/homework.feature
  page-objects/homework.js
  page-objects/pages/DashboardPage.js
  page-objects/pages/HMWRKHomeworkListPage.js
  page-objects/pages/NavigationTopPage.js
  page-objects/pages/teamsPages/TMSAddEditTeamPage.js
  shared_steps/firstLogin.js
  step_definitions/login-steps.js
Labels: waiting for review
