Repository hpi-schul-cloud/end-to-end-tests, pull requests merged in 2020-12, with the labels that each got.

#256 SC - 5780 - teacher edits team
  CHANGELOG.md
  features/management_classes/editClass.feature
  features/management_students/deleteStudent.feature
  features/teams/createTeam.feature
  features/teams/editTeam.feature
  page-objects/pages/DashboardPage.js
  page-objects/pages/teamsPages/TMSAddEditTeamPage.js
  page-objects/pages/teamsPages/TMSGeneralTeamPage.js
  page-objects/pages/teamsPages/TMSTeamListPage.js
  page-objects/pages/teamsPages/TMSTeamMembersPage.js
  step_definitions/courses/editCourse_steps.js
  step_definitions/teams/createTeam_steps.js
  step_definitions/teams/editTeam_steps copy.js
Labels: waiting for review

#261 SC - 6816 - new test @editClass
  CHANGELOG.md
  features/management_classes/editClass.feature
  page-objects/pages/managementPages/ManageClassPage.js
  page-objects/pages/managementPages/ManageClassesPage.js
  step_definitions/management_classes/createClass_steps.js
  step_definitions/management_classes/editClass_steps.js
Labels: waiting for review

#260 added new scenario for deletion concept
  features/management_students/deleteStudent.feature
  features/management_teachers/deleteTeacher.feature
  page-objects/pages/coursePages/CRSSEditCopyCoursePage.js
  page-objects/pages/managementPages/ManageCoursesPage.js
  page-objects/pages/managementPages/ManageStudentsPage.js
  page-objects/pages/managementPages/ManageTeachersPage.js
  step_definitions/management_teachers/deleteTeacher_steps.js
Labels: auto_merged, waiting for review

#229 Feature/reuse docker container
  .travis.yml
  CHANGELOG.md
  ci/config/notification-service/testplatform.config.json
  scripts/ci/end-to-end-tests.github.sh
  scripts/ci/end-to-end-tests.travis.sh
  scripts/ci/fetch.github.sh
  scripts/ci/fetch.travis.sh
  scripts/ci/integration-test.travis.sh
  scripts/ci/mailslurper-config.json
  scripts/ci/mailslurper-docker.sh
Labels: ready to merge

#265 new test: addGroupOfStudentsToTheClass
  CHANGELOG.md
  features/management_classes/editClass.feature
  features/management_students/deleteStudent.feature
  features/teams/createTeam.feature
  page-objects/pages/AccountPage.js
  page-objects/pages/NWSNewsListPage.js
  page-objects/pages/TASKAddEditTaskPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  page-objects/pages/managementPages/ManageClassPage.js
  page-objects/pages/managementPages/ManageCoursesPage.js
  page-objects/pages/teamsPages/TMSTeamMembersPage.js
  runtime/helpers/elementHelpers.js
  step_definitions/management_classes/createClass_steps.js
  step_definitions/management_classes/editClass_steps.js
  step_definitions/teams/createTeam_steps.js
Labels: waiting for review

#267 SC - 8120 - create new test createClassWith3Members
  CHANGELOG.md
  features/management_classes/createClass.feature
  page-objects/pages/managementPages/ManageClassesPage.js
  runtime/helpers/tableHelpers.js
  step_definitions/management_classes/createClass_steps.js
Labels: waiting for review

#268 SC-7848 - fix to fill current password due to new client bugfix
  CHANGELOG.md
  features/user_settings/changeLanguageMenu.feature
  page-objects/pages/AccountPage.js
  step_definitions/user_settings/changeLanguageMenu_steps.js
Labels: DO_NOT_MERGE, waiting for review

#269 SC-7126 - create a class with schoolYear due to bugfix on client
  CHANGELOG.md
  features/management_classes/createClass.feature
  features/management_classes/editClass.feature
  step_definitions/management_classes/createClass_steps.js
Labels: DO_NOT_MERGE, waiting for review
