Repository hpi-schul-cloud/end-to-end-tests, pull requests merged in 2020-04, with the labels that each got.

#56 Revert "added extra wait for teams-name"
  page-objects/createTeam.js
Labels: ready_to_merge

#44 add config for notification service
  ci/config/notification-service/testplatform.config.json
Labels: ready to merge

#57 feature/new admin routes
  features/createTeam.feature
  page-objects/administration.js
  shared-objects/administrationData.js
  step_definitions/createTeam-steps.js
Labels: waiting for review
