Repository hpi-schul-cloud/end-to-end-tests, pull requests merged in 2021-11, with the labels that each got.

#362 BC-402 - Update e2e test so there is an new workflow to call by other repos
  .github/workflows/e2e_call.yml
  CHANGELOG.md
Labels: waiting for review

#363 Feature/delete team
  CHANGELOG.md
  features/teams/deleteTeam.feature
  page-objects/pages/teamsPages/TMSGeneralTeamPage.js
  step_definitions/teams/createTeam_steps.js
  step_definitions/teams/deleteTeam_steps.js
  step_definitions/teams/editTeam_steps.js
Labels: waiting for review, run unstable tests

#364 Fix/BC-581 Improve E2E- deleteTask.feature
  features/management_students/deleteStudent.feature
  features/tasks/deleteTask.feature
  features/tasks/nuxtSubmitTask.feature
  page-objects/pages/TASKListPage.js
  step_definitions/management_students/createStudent_steps.js
  step_definitions/tasks/deleteTask_steps.js
Labels: WIP, waiting for review

#366 Feature/no ticket added create and edit teacher tests
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  features/management_teachers/createTeacher.feature
  features/management_teachers/editTeacher.feature
  page-objects/pages/managementPages/ManageStudentsPage.js
  page-objects/pages/managementPages/ManageTeacherPage.js
  page-objects/pages/managementPages/ManageTeachersPage.js
  step_definitions/management_students/createStudent_steps.js
  step_definitions/management_teachers/createTeacher_steps.js
  step_definitions/management_teachers/editTeacher_steps.js
Labels: waiting for review, run unstable tests

#372 feature/BC-611-nuxt-scenerio-improvement
  CHANGELOG.md
  features/tasks/deleteTask.feature
  features/tasks/nuxtSubmitTask.feature
  features/tasks/nuxtTeacherGradesTask.feature
  page-objects/pages/TASKListPage.js
  page-objects/pages/TASKPage.js
  runtime/helpers/waitHelpers.js
  step_definitions/tasks/nuxtSubmitTask_steps.js
Labels: WIP
