Repository hpi-schul-cloud/end-to-end-tests, pull requests merged in 2022-01, with the labels that each got.

#379 Feature/bc 978
  features/courses/copyCourse.feature
  features/courses/createCourse.feature
  features/courses/deleteCourse.feature
  features/courses/editCourse.feature
  features/courses/searchCourse.feature
  features/courses_topics/createTopic.feature
  features/courses_topics/deleteTopic.feature
  features/courses_topics/editTopic.feature
  features/dashboard/task.feature
  features/management_students/deleteStudent.feature
  features/management_teachers/deleteTeacher.feature
  features/navigation_bar_left/leftNavigationBar.feature
  features/rooms-overview.feature
  features/tasks/createTask.feature
  features/tasks/deleteTask.feature
  features/tasks/gradeTask.feature
  features/tasks/submitTask.feature
  page-objects/pages/NavigationLeftPage.js
  page-objects/pages/RoomsOverviewPage.js
  page-objects/pages/TASKPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  page-objects/pages/coursePages/CRSSAddEditTopicPage.js
  page-objects/pages/coursePages/CRSSCourseListPage.js
  page-objects/pages/coursePages/CRSSCourseTopicsPage.js
  page-objects/pages/coursePages/CRSSGeneralCoursePage.js
  step_definitions/courses/createCourse_steps.js
  step_definitions/courses/editCourse_steps.js
  step_definitions/courses_topics/createTopic_steps.js
  step_definitions/navigation_bar_left/leftNavigationBar_steps.js
  step_definitions/rooms-overview.js
  step_definitions/tasks/createTask_steps.js
Labels: waiting for review

#381 Feature/bc 919 navigation rooms overview
  features/courses/createCourse.feature
  features/user_settings/changeLanguageMenu.feature
  page-objects/pages/NavigationLeftPage.js
  page-objects/pages/RoomsOverviewPage.js
  page-objects/pages/coursePages/CRSSAddCoursePage.js
  step_definitions/courses/createCourse_steps.js
  step_definitions/courses_topics/createTopic_steps.js
  step_definitions/tasks/createTask_steps.js
Labels: ready to merge

#384 feature/BC-538-edit-action-task-item
  features/tasks/editTask.feature
  page-objects/pages/TASKListPage.js
  runtime/helpers/elementHelpers.js
  step_definitions/tasks/createTask_steps.js
  step_definitions/tasks/editTask_steps.js
Labels: WIP, waiting for review

#387 Refactor task scenarios
  features/dashboard/task.feature
  features/tasks/deleteTask.feature
  features/tasks/editTask.feature
  features/tasks/gradeTask.feature
  features/tasks/submitTask.feature
  page-objects/pages/TASKListPage.js
  page-objects/pages/TASKPage.js
  runtime/helpers/elementHelpers.js
Labels: enhancement, WIP, waiting for review, run unstable tests
